server:
  port: 9190

logging:
  level:
    org.springframework.security: trace

spring:
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          resource-identifier: test-client
          issuer-uri: http://localhost:8080/realms/master
          audiences: account
